version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: pepys-api
          RAILS_ENV: test
          DATABASE_URL: "postgres://pepys-api:@127.0.0.1:5432/pepys-api_test"
      - image: circleci/postgres:11.1-alpine
        environment:
          POSTGRES_USER: pepys-api
          POSTGRES_DB: pepys-api_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/pepys-api
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:create db:schema:load --trace

      # Run rspec in parallel
      - run:
          name: Run tests
          command: bundle exec rake test

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
