version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/ruby:2.6.0-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: pepys-api
          RAILS_ENV: test
      - image: circleci/postgres:11.1-alpine
        environment:
          POSTGRES_USER: pepys-api
          POSTGRES_DB: pepys-api_development
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - pepys-api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - pepys-api-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: pepys-api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # Run rspec in parallel
      - run:
          name: Run rspec in parallel
          command: bin/rails test

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
